//Caesar ROT7
const genres = {
  drama: 'kyhth',
  romance: 'yvthujl',
  comedy: 'jvtlkf',
  action: 'hjapvu',
  thriller: 'aoypssly',
  mystery: 'tfzalyf',
  crime: 'jyptl',
  horror: 'ovyyvy',
  family: 'mhtpsf',
  fantasy: 'mhuahzf',
  historical: 'opzavypjhs',
  adventure: 'hkcluabyl',
  melodrama: 'tlsvkyhth',
  suspense: 'zbzwluzl',
  school: 'zjovvs',
  scifi: 'zjpmp',
  medical: 'tlkpjhs',
  music: 'tbzpj',
  sports: 'zwvyaz',
  detective: 'klaljapcl',
  martialarts: 'thyaphshyaz',
  war: 'dhy',
  dating: 'khapun',
  reality: 'ylhspaf',
  variety: 'chyplaf',
};
